# Generated by Django 4.2.4 on 2023-11-02 13:12

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_book_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPersonDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(validators=[main_app.validators.validate_age])),
            ],
        ),
    ]
