# Generated by Django 4.2.4 on 2023-11-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_edited_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
