# Generated by Django 4.2.4 on 2023-11-02 19:13
import random

from django.db import migrations


def add_barcode(app, schema_editor):
    Product = app.get_model("main_app", "Product")
    all_products = Product.objects.all()
    all_barcodes = random.sample(
        range(100000000, 999999999), len(all_products)
    )
    print(all_barcodes)

    for i in range(len(all_products)):
        product = all_products[i]
        product.barcode = all_barcodes[i]
        product.save()


def reverse_add_barcode(app, schema_editor):
    Product = app.get_model("main_app", "Product")
    for product in Product.objects.all():
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_code=reverse_add_barcode)
    ]
