# Generated by Django 4.2.4 on 2023-11-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_taskencoder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskEncoder',
            new_name='Task',
        ),
    ]
