# Generated by Django 4.2.4 on 2023-11-09 08:47

from django.db import migrations


def set_age_group(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    all_persons = person_model.objects.all()

    for p_rec in all_persons:
        if p_rec.age <= 12:
            p_rec.age_group = 'Child'
        elif p_rec.age <= 17:
            p_rec.age_group = 'Teen'
        else:
            p_rec.age_group = 'Adult'

    person_model.objects.bulk_update(all_persons, ['age_group'])


def set_age_group_default(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')

    all_persons = person_model.objects.all()

    age_group_default = person_model._meta.get_field("age_group").default  # No age group

    for p_rec in all_persons:
        p_rec.age_group = age_group_default

    person_model.objects.bulk_update(all_persons, ['age_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=set_age_group_default)
    ]
