# Generated by Django 4.2.4 on 2023-11-09 09:06

from django.db import migrations


def set_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    all_items = item_model.objects.all()

    for i_rec in all_items:
        if i_rec.price <= 10:
            i_rec.rarity = 'Rare'
        elif i_rec.price <= 20:
            i_rec.rarity = 'Very Rare'
        elif i_rec.price <= 30:
            i_rec.rarity = 'Extremely rare'
        else:
            i_rec.rarity = 'Mega Rare'

    item_model.objects.bulk_update(all_items, ['rarity'])


def set_rarity_default(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    all_items = item_model.objects.all()

    rarity_default = item_model._meta.get_field('rarity').default

    for i_rec in all_items:
        i_rec.rarity = rarity_default

    item_model.objects.bulk_update(all_items, ['rarity'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity, reverse_code=set_rarity_default)
    ]
