# Generated by Django 4.2.4 on 2023-11-09 09:31

from django.db import migrations


def set_price(apps, schema_editor):
    CONST_PRICE = 120

    smartphone_model = apps.get_model('main_app', 'Smartphone')

    all_smartphones = smartphone_model.objects.all()

    for s_rec in all_smartphones:
        s_rec.price = len(s_rec.brand) * CONST_PRICE

    smartphone_model.objects.bulk_update(all_smartphones, ['price'])


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    all_smartphones = smartphone_model.objects.all()

    for s_rec in all_smartphones:
        if s_rec.price >= 750:
            s_rec.category = 'Expensive'
        else:
            s_rec.category = 'Cheap'

    smartphone_model.objects.bulk_update(all_smartphones, ['category'])


def set_both(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def set_both_default(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    all_smartphones = smartphone_model.objects.all()

    price_default = smartphone_model._meta.get_field('price').default
    category_default = smartphone_model._meta.get_field('category').default

    for s_rec in all_smartphones:
        s_rec.price = price_default
        s_rec.category = category_default

    smartphone_model.objects.bulk_update(all_smartphones, ['price', 'category'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_both, reverse_code=set_both_default)
    ]
