# Generated by Django 4.2.4 on 2023-11-09 09:51

from django.db import migrations
from django.utils import timezone


def update_delivery_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    all_orders = order_model.objects.all()

    for o_rec in all_orders:
        if o_rec.status == "Pending":
            o_rec.delivery = o_rec.order_date + timezone.timedelta(days=3)
        elif o_rec.status == "Completed":
            o_rec.warranty = "24 months"
        elif o_rec.status == "Canceled":
            o_rec.delete()

    order_model.objects.bulk_update(all_orders, ['delivery', 'warranty'])


def reverse_delivery_and_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    all_orders = order_model.objects.all()

    delivery_default = order_model._meta.get_field('delivery').default
    warranty_default = order_model._meta.get_field('warranty').default

    for o_rec in all_orders:
        if o_rec.status == "Pending":
            o_rec.delivery = delivery_default
        elif o_rec.status == "Completed":
            o_rec.warranty = warranty_default

    order_model.objects.bulk_update(all_orders, ['delivery', 'warranty'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_order'),
    ]

    operations = [
    ]
