# Generated by Django 4.2.4 on 2023-11-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_document'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['search_vector'], name='main_app_do_search__c97410_idx'),
        ),
    ]
